// padding of grid, generated by path finding
export const GRID_PADDING = 150;
// scale factor, for minimize grid size
export const SCALE_FACTOR = 5;

export const DEFAULT_NODE_PADDING = SCALE_FACTOR * 2;

export const DEFAULT_PORT_GAP = SCALE_FACTOR * 2;

export const DEFAULT_MIN_ZOOM = 0.5;
export const DEFAULT_MAX_ZOOM = 1.5;
