import {
  IGetters, PortDirection,
} from '@/types';

// padding of grid, generated by path finding
export const GRID_PADDING = 150;
// scale factor, for minimize grid size
export const SCALE_FACTOR = 5;

export const DEFAULT_NODE_PADDING = SCALE_FACTOR * 2;

export const DEFAULT_PORT_GAP = SCALE_FACTOR * 2;

export const DEFAULT_MIN_ZOOM = 0.5;
export const DEFAULT_MAX_ZOOM = 1.5;

/* eslint-disable @typescript-eslint/no-explicit-any */
export const DEFAULT_GETTERS: IGetters = {
  getNodePosition (node: any) {
    return { x: node.x, y: node.y };
  },
  getNodeSize (node: any) {
    return { width: node.width, height: node.height };
  },
  getNodePorts (node: any) {
    return node.ports;
  },
  getNodePort (node: any, portId: string) {
    const ports = this.getNodePorts(node);
    return ports[portId];
  },
  getPortDirection (port: any) {
    return port.direction;
  },
  getPortPosition (node: any, port: any) {
    const { x, y } = this.getNodePosition(node);
    const { width, height } = this.getNodeSize(node);
    switch (this.getPortDirection(port)) {
      case PortDirection.TOP:
        return { x: x + width / 2, y };
      case PortDirection.LEFT:
        return { x, y: y + height / 2 };
      case PortDirection.RIGHT:
        return { x: x + width, y: y + height / 2 };
      default:
        return { x: x + width / 2, y: y + height };
    }
  },
  getNode (nodes: any, nodeId: string) {
    return nodes[nodeId];
  },
  getFromNodeIdOfLink (link) {
    return link.from.nodeId;
  },
  getToNodeIdOfLink (link) {
    return link.to.nodeId;
  },
  getFromPortIdOfLink (link) {
    return link.from.portId;
  },
  getToPortIdOfLink (link) {
    return link.to.portId;
  },
  getDraftPortOfLink (link: any) {
    return { position: link.mousePosition };
  },
  isDraftLink (link: any) {
    return !(link.to && link.to.portId);
  },
  getLinkIdentifier (link: any) {
    return link.id;
  },
  getNodeIdentifier (node: any) {
    return node.id;
  },
  getPortIdentifier (port: any) {
    return port.id;
  },
};
/* eslint-enable @typescript-eslint/no-explicit-any */
